name: robot_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-76.0.dev

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.11
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
